version: "3.9"

services:
  bitcoind:
    build: .
    container_name: bitcoind
    restart: unless-stopped
    cpus: 1.0
    mem_limit: "512M"
    ports:
      # - 8332:8332 # mainnet rpcport
      - 18332:18332 # testnet rpcport
    networks:
      - bloknodes-network
    volumes:
      - bloknodes-volume:/blockchain

networks:
  bloknodes-network:
    name: bloknodes-network
    
volumes:
  bloknodes-volume: {}
